name: run-tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  golangci:
    name: golangci-lint
    concurrency:
      group: lint-golangci-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # because we use new-from-rev in golangci-lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
      - name: golangci-lint-new-code-much-stricter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --verbose --disable-all --new-from-rev=origin/master --enable stylecheck,funlen

  tests:
    name: run tests
    concurrency:
      group: tests-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      - name: download dependencies
        run: |
          go mod download
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: build ydbops
        run: make build
      - name: run tests
        run: go test -v -p 1 ./... -args -ginkgo.v 
